--cau 4
--ALTER TABLE PHONGBAN
--ALTER COLUMN TenPhg nvarchar(30);
--ALTER TABLE DEAN
--ALTER COLUMN DDiemDA nvarchar(20);
--ALTER TABLE THANNHAN
--ALTER COLUMN TenTN nvarchar(20);
--ALTER COLUMN Phai nvarchar(3);
--ALTER COLUMN QuanHe nvarchar(15);
